#ifndef X
#error "X macro must be defined"
#endif

X(Ast_source, AstSource)
X(Ast_mod_section, AstModSection)
X(Ast_block, AstBlock)
X(Ast_type_slice, AstTypeSlice)
X(Ast_type_array, AstTypeArray)
X(Ast_type_function, AstTypeFunction)
X(Ast_builtin, AstBuiltin)
X(Ast_declaration, AstDeclaration)
X(Ast_assign, AstAssign)
X(Ast_literal_int, TokenIndex)
X(Ast_literal_string, TokenIndex)
X(Ast_identifier, TokenIndex)
X(Ast_call, AstCall)
X(Ast_index, AstIndexData)
X(Ast_unary_op, AstUnaryOp)
X(Ast_binary_op, AstBinaryOp)
X(Ast_function, AstFunction)
X(Ast_param, AstParam)
X(Ast_if_else, AstIfElse)
X(Ast_for, AstFor)
X(Ast_defer, AstDefer)
X(Ast_const, AstConst)
X(Ast_cast, AstCast)
X(Ast_as, AstAs)
