#ifndef X
#error "X macro must be defined"
#endif

X(Ast_source,         AstSource,       "source")
X(Ast_mod_section,    AstModSection,   "mod_section")
X(Ast_block,          AstBlock,        "block")
X(Ast_type_slice,     AstTypeSlice,    "type_slice")
X(Ast_type_array,     AstTypeArray,    "type_array")
X(Ast_type_function,  AstTypeFunction, "type_function")
X(Ast_builtin,        AstBuiltin,      "builtin")
X(Ast_declaration,    AstDeclaration,  "declaration")
X(Ast_assign,         AstAssign,       "assign")
X(Ast_literal_int,    TokenIndex,      "literal-int")
X(Ast_literal_string, TokenIndex,      "literal_string")
X(Ast_literal_u8_string, TokenIndex,   "literal_u8_string")
X(Ast_identifier,     TokenIndex,      "identifier")
X(Ast_label,          TokenIndex,      "label")
X(Ast_call,           AstCall,         "call")
X(Ast_index,          AstIndexData,    "index")
X(Ast_unary_op,       AstUnaryOp,      "unary_op")
X(Ast_binary_op,      AstBinaryOp,     "binary_op")
X(Ast_function,       AstFunction,     "function")
X(Ast_param,          AstParam,        "param")
X(Ast_if_else,        AstIfElse,       "if_else")
X(Ast_while,          AstWhile,        "while")
X(Ast_break,          AstBreak,        "break")
X(Ast_cast,           AstCast,         "cast")
