#ifndef X
#error "X macro must be defined"
#endif

X(IR_func,                 True,  IrFunc,        "func")
X(IR_arg,                  False, u32,          "arg")
X(IR_alloc,                False, u32,          "alloc")
X(IR_cond_br,              True,  IrCondBr,      "cond-br")
X(IR_block,                False, u32,          "block")
X(IR_loop,                 False, u32,          "loop")
X(IR_br,                   False, u32,          "br")
X(IR_repeat,               False, u32,          "repeat")
X(IR_ret,                  False, u32,          "ret")
X(IR_load,                 False, u32,          "load")
X(IR_store,                True,  IrStore,       "store")
X(IR_call,                 True,  IrCall,        "call")
X(IR_declaration,          True,  IrDeclaration, "declaration")
X(IR_lookup,               False, u32,          "lookup")
X(IR_cast_int,             True,  IrCastInt,     "cast-int")
X(IR_cast_int_safe,        True,  IrCastInt,     "cast-int-safe")
X(IR_as,                   True,  IrAs,          "as")
X(IR_unify,                True,  IrUnify,       "unify")
X(IR_type,                 True,  IrType,        "type")
X(IR_typeof,               False, u32,          "typeof")
X(IR_typeinfo,             False, u32,          "typeinfo")
X(IR_function_return_type, False, u32,          "function-return-type")
