#ifndef X
#error "X macro must be defined"
#endif

X(SIR_func,              "func",              True,  SIrFunc)
X(SIR_param,             "param",             False, u32)
X(SIR_alloc,             "alloc",             False, u32)
X(SIR_load,              "load",              False, u32)
X(SIR_store,             "store",             True,  SIrStore)
X(SIR_block,             "block",             False, u32)
X(SIR_loop,              "loop",              False, u32)
X(SIR_condbr,            "condbr",            True,  SIrCondbr)
X(SIR_br,                "br",                True,  SIrBr)
X(SIR_repeat,            "repeat",            False, u32)
X(SIR_ret,               "ret",               False, u32)
X(SIR_call,              "call",              True,  SIrCall)
X(SIR_and,               "and",               True,  SIrBinary)
X(SIR_or,                "or",                True,  SIrBinary)
X(SIR_mul,               "mul",               True,  SIrBinary)
X(SIR_div,               "div",               True,  SIrBinary)
X(SIR_mod,               "mod",               True,  SIrBinary)
X(SIR_sub,               "sub",               True,  SIrBinary)
X(SIR_add,               "add",               True,  SIrBinary)
X(SIR_cmp_eq,            "cmp_eq",            True,  SIrBinary)
X(SIR_cmp_ne,            "cmp_ne",            True,  SIrBinary)
X(SIR_cmp_gt,            "cmp_gt",            True,  SIrBinary)
X(SIR_cmp_ge,            "cmp_ge",            True,  SIrBinary)
X(SIR_cmp_lt,            "cmp_lt",            True,  SIrBinary)
X(SIR_cmp_le,            "cmp_le",            True,  SIrBinary)
X(SIR_index,             "index",             True,  SIrBinary)
X(SIR_negate,            "negate",            False, u32)
X(SIR_not,               "not",               False, u32)
X(SIR_builtin_debug,     "#debug",            False, u32)
X(SIR_comptime_block,    "comptime_block",    False, u32)
X(SIR_lookup_decl_value, "lookup_decl_value", False, u32)
X(SIR_lookup_decl_type,  "lookup_decl_type",  False, u32)
X(SIR_comptime_alloc,    "comptime_alloc",    False, u32)
X(SIR_as,                "as",                True,  SIrAs)
X(SIR_unify,             "unify",             True,  SIrUnify)
X(SIR_type,              "type",              True,  SIrType)
X(SIR_typeof,            "typeof",            False, u32)
X(SIR_base_type,         "base_type",         False, u32)
X(SIR_return_type,       "return_type",       False, u32)
X(SIR_param_type,        "param_type",        True,  SIrParamType)
